env:
  CIRRUS_CLONE_DEPTH: 1
  GO_VERSION: go1.25.5

freebsd_14_task:
  freebsd_instance:
    image_family: freebsd-14-3
  install_script: |
    pkg install -y go
    GOBIN=$PWD/bin go install golang.org/dl/${GO_VERSION}@latest
    bin/${GO_VERSION} download
  build_script: bin/${GO_VERSION} build -v ./...
  test_script: bin/${GO_VERSION} test -race ./...

freebsd_15_task:
  freebsd_instance:
    image_family: freebsd-15-0-amd64-zfs
  install_script: |
    pkg install -y go
    GOBIN=$PWD/bin go install golang.org/dl/${GO_VERSION}@latest
    bin/${GO_VERSION} download
  build_script: bin/${GO_VERSION} build -v ./...
  test_script: bin/${GO_VERSION} test -race ./...
