// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs sysconf_defs_linux.go

package sysconf

const (
	SC_ARG_MAX        = 0x0
	SC_CHILD_MAX      = 0x1
	SC_HOST_NAME_MAX  = 0xb4
	SC_LOGIN_NAME_MAX = 0x47
	SC_NGROUPS_MAX    = 0x3
	SC_CLK_TCK        = 0x2
	SC_OPEN_MAX       = 0x4
	SC_PAGESIZE       = 0x1e
	SC_RE_DUP_MAX     = 0x2c
	SC_STREAM_MAX     = 0x5
	SC_SYMLOOP_MAX    = 0xad
	SC_TTY_NAME_MAX   = 0x48
	SC_TZNAME_MAX     = 0x6
	SC_VERSION        = 0x1d

	SC_BC_BASE_MAX      = 0x24
	SC_BC_DIM_MAX       = 0x25
	SC_BC_SCALE_MAX     = 0x26
	SC_BC_STRING_MAX    = 0x27
	SC_COLL_WEIGHTS_MAX = 0x28
	SC_EXPR_NEST_MAX    = 0x2a
	SC_LINE_MAX         = 0x2b
	SC_2_VERSION        = 0x2e
	SC_2_C_DEV          = 0x30
	SC_2_C_VERSION      = 0x60
	SC_2_FORT_DEV       = 0x31
	SC_2_FORT_RUN       = 0x32
	SC_2_LOCALEDEF      = 0x34
	SC_2_SW_DEV         = 0x33

	SC_PHYS_PAGES       = 0x55
	SC_AVPHYS_PAGES     = 0x56
	SC_NPROCESSORS_CONF = 0x53
	SC_NPROCESSORS_ONLN = 0x54
)

const (
	_POSIX_VERSION  = 0x31069
	_POSIX2_VERSION = 0x31069

	_POSIX2_C_DEV     = 0x31069
	_POSIX2_C_VERSION = 0x31069

	_POSIX_ARG_MAX   = 0x1000
	_POSIX_CHILD_MAX = 0x19

	_HOST_NAME_MAX  = 0x40
	_LOGIN_NAME_MAX = 0x100
	_NGROUPS_MAX    = 0x10000
	_RE_DUP_MAX     = 0x7fff
	_STREAM_MAX     = 0x10
	_SYMLOOP_MAX    = -0x1
	_TTY_NAME_MAX   = 0x20
	_TZNAME_MAX     = 0x6

	_BC_BASE_MAX      = 0x63
	_BC_DIM_MAX       = 0x800
	_BC_SCALE_MAX     = 0x63
	_BC_STRING_MAX    = 0x3e8
	_COLL_WEIGHTS_MAX = 0xff
	_EXPR_NEST_MAX    = 0x20
	_LINE_MAX         = 0x800
)
